### PR TITLE
Main Menu Rework, Settings menu, and Back to Main Menu and Restart Buttons

### PR DESCRIPTION
**Pull request by jamilfaisal**
LOTTA NEW THINGS IN THIS PR SORRY I GOT CARRIED AWAY

- Main menu rework (background adjusted, NEW "Press Enter to select" icon if no gamepad is plugged in, and buttons are now horizontal to make space for the settings button)
- Settings menu (Fullscreen option, Graphics Quality settings, Music and Sound Effect volumes)
- Player settings are locally saved (Applies to all settings)
- Back to Main Menu button in pause screen of level one
- Settings button in pause screen of level one

P.S. I was messing around with Adaptive Performance but I dont think we need it so I removed it (there's still traces of it for some reason pls ignore)

### CODE REVIEW

**Review by lilvedaes — COMMENTED** [review]
On my side everything worked well c: only thing is that when you open settings in the game the image doesn't fill the whole screen. Is this intended or is it a resolution issue? 
image

**Comment by judy-n** [comment]
Wow amazing work!! I love the settings, the volume stuff is so impressive too how it plays a meow sound when you change the sound effects volume

**Comment by judy-n** [comment]
> On my side everything worked well c: only thing is that when you open settings in the game the image doesn't fill the whole screen. Is this intended or is it a resolution issue?
> image

I also had a comment about this screen, I think it should have no background when it's opened from inside the game. I think it should be the same as how we have the pause screen overlaying on top of the game. Because the yellow background looks a bit random here since it's from the main menu

**Comment by judy-n** [comment]
Another note about the settings, I think the blue color is a little strong, like the "Settings" title is a bit hard to read. I think we should try different colors, I'd be happy to play around with that if you want.

**Comment by jamilfaisal** [comment]
> > On my side everything worked well c: only thing is that when you open settings in the game the image doesn't fill the whole screen. Is this intended or is it a resolution issue?
> > image
> 
> I also had a comment about this screen, I think it should have no background when it's opened from inside the game. I think it should be the same as how we have the pause screen overlaying on top of the game. Because the yellow background looks a bit random here since it's from the main menu

Got rid of it

**Comment by jamilfaisal** [comment]
> Another note about the settings, I think the blue color is a little strong, like the "Settings" title is a bit hard to read. I think we should try different colors, I'd be happy to play around with that if you want.

Sounds good to me. Make sure to change it in both scenes 👍

**Comment by judy-n** [comment]
And about the main menu, the "Press enter" looks great! 
With the buttons, I thought it makes more sense if its Start -> Settings -> Quit, rather than the start button being sandwiched between them. In games I'm used to the Start/Play being the first button.

Also it may be better to have the buttons stack vertically, if we maybe put the "Meow Tunes" higher in the screen and have more space. What do you guys think? It can also be done in another task later if we need to modify the background image.

**Comment by jamilfaisal** [comment]
> And about the main menu, the "Press enter" looks great! With the buttons, I thought it makes more sense if its Start -> Settings -> Quit, rather than the start button being sandwiched between them. In games I'm used to the Start/Play being the first button.
> 
> Also it may be better to have the buttons stack vertically, if we maybe put the "Meow Tunes" higher in the screen and have more space. What do you guys think? It can also be done in another task later if we need to modify the background image.

Yeahhhhhh I just googled "video game main menus" and most of em do vertical, so that's probably the route we should go with, Ill change it

**Review by judy-n — APPROVED** [review]
LGTM! Good job :)

**Review by lilvedaes — APPROVED** [review]
Thanks for all the reworks!

**Pull request merged**
