### PR TITLE
Add UI for the Countdown at start of level

### PR DESCRIPTION
**Pull request by judy-n**
- added text at the start that says "Start in" and the count below it

### CODE REVIEW

**Review by lilvedaes — COMMENTED** [review]
Can we add a sound effect to each countdown tick?

**Comment by judy-n** [comment]
> Can we add a sound effect to each countdown tick?

Added!

**Review by lilvedaes — APPROVED** [review]
Very aesthetic countdown effect! thank you c:

**Review by jamilfaisal — CHANGES_REQUESTED** [review]
Good work! One last thing, can you add the count down sound effect to MusicPlayer.cs, so that the sound effect volume (set in settings) is applied to the count down sound?  Thanks!

**Comment by judy-n** [comment]
> Good work! One last thing, can you add the count down sound effect to MusicPlayer.cs, so that the sound effect volume (set in settings) is applied to the count down sound? Thanks!

Added it :)

**Review by jamilfaisal — APPROVED** [review]
Good work!

**Pull request merged**
