### PR TITLE
Fix Pause button bug on controller

### PR DESCRIPTION
**Pull request by judy-n**

### CODE REVIEW

**Comment by jamilfaisal** [comment]
Yay it works, but I can't actually select the options. Dpad, left stick, all the buttons except for START don't do anything. START just unpauses the game. I can select the options in the main menu though, maybe you can compare the main menu and the pause screen controls?

Also I noticed the player's speed goes to 0 when the game is paused. This is a bug since the player will be off-beat when we implement the MIDI stuff. Should I create another ticket or do you think you can quickly fix it in this PR?

**Comment by judy-n** [comment]
> Yay it works, but I can't actually select the options. Dpad, left stick, all the buttons except for START don't do anything. START just unpauses the game. I can select the options in the main menu though, maybe you can compare the main menu and the pause screen controls?
> 
> Also I noticed the player's speed goes to 0 when the game is paused. This is a bug since the player will be off-beat when we implement the MIDI stuff. Should I create another ticket or do you think you can quickly fix it in this PR?

thanks for catching that, I fixed the selecting options bug. Turns out the "Default selected" thing in the Event system was set to "none".

For the other thing, I looked at it quickly now but Im not sure if I have a quick fix. Because currently we disable the playerMovement script when we pause the game

**Comment by jamilfaisal** [comment]
> > Yay it works, but I can't actually select the options. Dpad, left stick, all the buttons except for START don't do anything. START just unpauses the game. I can select the options in the main menu though, maybe you can compare the main menu and the pause screen controls?
> > Also I noticed the player's speed goes to 0 when the game is paused. This is a bug since the player will be off-beat when we implement the MIDI stuff. Should I create another ticket or do you think you can quickly fix it in this PR?
> 
> thanks for catching that, I fixed the selecting options bug. Turns out the "Default selected" thing in the Event system was set to "none".
> 
> For the other thing, I looked at it quickly now but Im not sure if I have a quick fix. Because currently we disable the playerMovement script when we pause the game

Nice, I'll check it out. For the player speed thing, we can implement a count down (the same one we'll implement for when the player respawns) after the player unpauses, and we just set the player velocity to how it was before the pause

**Comment by jamilfaisal** [comment]
Lol ok so I can pick the options but I think it carries over to the game. The button to select the option on my 8bitdo controller is the same button for jumping. If I hover over "Resume", and click and hold down the jump button for 0.7 seconds, the cat does a mini hop in the game. If I hover over "Resume", and click and hold down the jump button for 3 seconds, the cat does a BIG jump in the game. I guess we can fix this if we have the countdown as well

**Comment by judy-n** [comment]
> Lol ok so I can pick the options but I think it carries over to the game. The button to select the option on my 8bitdo controller is the same button for jumping. If I hover over "Resume", and click and hold down the jump button for 0.7 seconds, the cat does a mini hop in the game. If I hover over "Resume", and click and hold down the jump button for 3 seconds, the cat does a BIG jump in the game. I guess we can fix this if we have the countdown as well

I've been trying to fix this but can't get it to work unfortunately

**Comment by jamilfaisal** [comment]
> 

Ok, make sure to bump up the countdown feature in terms of priority bc this is a major annoyance imo

**Review by jamilfaisal — APPROVED** [review]

**Review by lilvedaes — APPROVED** [review]
Works great for me!!!

**Pull request merged**
