### PR TITLE
Minor UI Fixes and Default Music Adjustments

### PR DESCRIPTION
**Pull request by jamilfaisal**
- Change fish treat score UI to match player lives UI (add "x") 
- Change "Perfect!" to "Purr-fect!" 
- Lower default music and sound effects volume

### CODE REVIEW

**Review by judy-n — COMMENTED** [review]
UI looks good!
I was wondering, did you lower the footsteps volume or just sound effects as a whole? I can still hear the footsteps if I pay attention and it messes with a rhythm a bit

**Comment by jamilfaisal** [comment]
> UI looks good! I was wondering, did you lower the footsteps volume or just sound effects as a whole? I can still hear the footsteps if I pay attention and it messes with a rhythm a bit

Oh I did it as a whole. Should I just lower the footsteps to like 5%? (Right now all sound effects are 15%)

**Review by Gavin-L26 — APPROVED** [review]

**Comment by judy-n** [comment]
> > UI looks good! I was wondering, did you lower the footsteps volume or just sound effects as a whole? I can still hear the footsteps if I pay attention and it messes with a rhythm a bit
> 
> Oh I did it as a whole. Should I just lower the footsteps to like 5%? (Right now all sound effects are 15%)

Yep I definitely think you should lower them specifically

**Comment by jamilfaisal** [comment]
> > > UI looks good! I was wondering, did you lower the footsteps volume or just sound effects as a whole? I can still hear the footsteps if I pay attention and it messes with a rhythm a bit
> > 
> > 
> > Oh I did it as a whole. Should I just lower the footsteps to like 5%? (Right now all sound effects are 15%)
> 
> Yep I definitely think you should lower them specifically

Ok I decreased the footsteps volume by 30% of the sound effects volume (so default for footsteps is now 5%). It sounded awkward because the land jump that happens right before the footsteps sound is really loud in comparison so I lowered that too. Give it a try please :)

**Review by judy-n — APPROVED** [review]
That's perfect!! Good job 👑

**Pull request merged**
