### PR TITLE
Implement timer and Display Score and Time on Win screen

### PR DESCRIPTION
**Pull request by jamilfaisal**
- Implement timer (pauses during pause screen, ends when player wins or loses)
- Update Win level animation to display score and time
- Code refactoring

### CODE REVIEW

**Review by judy-n — COMMENTED** [review]
Great work! 👌 Timer really adds fun to the game
One thing I wanted us to discuss is if we should show milliseconds? It looks like a lot on the screen, I'm not sure if it's necessary. or maybe if we do show them, then we only show 1-2 decimal points rather than 3. 
@lilvedaes would love your input on this!

**Comment by jamilfaisal** [comment]
> Great work! 👌 Timer really adds fun to the game One thing I wanted us to discuss is if we should show milliseconds? It looks like a lot on the screen, I'm not sure if it's necessary. or maybe if we do show them, then we only show 1-2 decimal points rather than 3. @lilvedaes would love your input on this!

Great question! I think it ultimately comes down to what the point of this timer is. I imagined this timer is only really for the speedrunners (as I mentioned in our last meeting, having the timer on the screen will encourage players to rush through the level as fast as they can - which I don't think is the point of our game). As such, I imagined the timer will be turned off by default and players can turn it on the settings menu if they like. So, a better question is would speedrunners care to see the milliseconds while they're playing? Personally, when I was playing, the last 2 digits were unreadable because they were flipping through 0-9 so fast that you can't actually read what the number is haha. I only kept it because it looked cool lol. I've considered it more and I think the best thing to do is to only show minutes and seconds BUT we show minutes, seconds, and milliseconds (3 digits) in the Win end screen (and in the future highscore board)

@lilvedaes What do you think?

**Comment by lilvedaes** [comment]
> @lilvedaes What do you think?

Sorry, somehow this got past my email. Yeah for now the timer is just for the people that care about their finish time (for example speedrunners). Last meeting I believe we said the timer would by default only show in the Win end screen unless they change their settings to display the timer while they are playing. I think they care about milliseconds and it would also be inconsistent to not have both timers look the same (if we had one without milliseconds and one with). I think 00:00:00 works well for both (so I agree with Judy about only the first two millisecond digits, that's also how the apple timer looks).

**Review by lilvedaes — APPROVED** [review]
LGTM c:

**Review by Gavin-L26 — APPROVED** [review]

**Pull request merged**
