### PR TITLE
Final score should be rhythm score multiplied by fish score

### PR DESCRIPTION
**Pull request by lilvedaes**
Notes: When playing, I had a lot of trouble with one of the last platforms where you have to jump up, it was almost impossible to get.

### CODE REVIEW

**Comment by jamilfaisal** [comment]
The score starts off to the right of the text, but when you reach 4-digits, it goes underneath the text. It should be one or the other imo
image
image

**Comment by jamilfaisal** [comment]
I guess it's unrelated to this PR, but you can spam the jump button to get 50 score over and over. Kinda defeats the purpose of trying to follow the beat when you can just spam and get a higher score.
image
image

**Comment by jamilfaisal** [comment]
I feel like the text at the end appears way too quickly. Can we please slow it down by a little bit? (just a tiny bit)

**Comment by lilvedaes** [comment]
> I guess it's unrelated to this PR, but you can spam the jump button to get 50 score over and over. Kinda defeats the purpose of trying to follow the beat when you can just spam and get a higher score. image image

Yeah there's already a ticket to fix that, its assigned to gavin c: We should also make note that its very easy to get perfect

**Comment by lilvedaes** [comment]
> I feel like the text at the end appears way too quickly. Can we please slow it down by a little bit? (just a tiny bit)

will do rn c:

**Comment by judy-n** [comment]
I can't actually try playing this today, but looking at the end screen that Faisal sent, the "Final score" number doesn't read nicely... maybe it should stand out more from the multiplication? Bc right now all those numbers look the same.

Maybe the score could be big and bold, and the multiplication is small and above the score, so you see where we got it but it doesnt jump at you. And maybe to improve readability we can add commas in the numbers? so like "1,189,250". Since the number is huge

**Review by judy-n — APPROVED** [review]
Love it

**Review by jamilfaisal — APPROVED** [review]

**Pull request merged**
