### PR TITLE
Remove joystick movement for going Left/Right 

### PR DESCRIPTION
**Pull request by judy-n**
- can only use Dpad on controller to go left or right.

### CODE REVIEW

**Review by lilvedaes — APPROVED** [review]
LGTM C:

**Review by jamilfaisal — COMMENTED** [review]
Yep sticks don't work to move left/right on my xbox and 8bitdo controllers. Good work!

@lilvedaes should we also remove sticks from working in menus? I think if the player uses the stick to control the menu, but can't use them in-game, they could be confused (because they used sticks to navigate left/right to change the volumes but now they have to use d-pad) 🤔

**Comment by lilvedaes** [comment]
> Yep sticks don't work to move left/right on my xbox and 8bitdo controllers. Good work!
> 
> @lilvedaes should we also remove sticks from working in menus? I think if the player uses the stick to control the menu, but can't use them in-game, they could be confused (because they used sticks to navigate left/right to change the volumes but now they have to use d-pad) 🤔

Oh yeah that's a good note, they should also not work in the menu

**Review by jamilfaisal — APPROVED** [review]
niceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Review by lilvedaes — APPROVED** [review]
Reapproved

**Pull request merged**
