### PR TITLE
Player gets stuck on walls FIX

### PR DESCRIPTION
**Pull request by jamilfaisal**
- Player gets teleported to where they are supposed to be based on the music time, when they get stuck on a platform or die and respawn back to a checkpoint
- Teleport sound effect plays
- Animation not implemented yet

### CODE REVIEW

**Review by lilvedaes — COMMENTED** [review]
It works perfectly, but the teleportation to way ahead when the side movement happens is really big :c could the "Moving left/right slows the player and causes desync" ticket be part of this PR as well?

**Comment by Gavin-L26** [comment]
image
I think for many checkpoint the spawning location's y value is too low, I keep getting respawned like this.

**Comment by jamilfaisal** [comment]
> image I think for many checkpoint the spawning location's y value is too low, I keep getting respawned like this.

Should be fixed now 👍

**Comment by Gavin-L26** [comment]
> > image I think for many checkpoint the spawning location's y value is too low, I keep getting respawned like this.
> 
> Should be fixed now 👍

Yep it is. Like I mentioned on discord, the quickest solve for desync right now is to tweak the SideMovementZOffest variable for the Player, the original value was 11 which works perfectly for my desktop at home, but not other computers. I suggest decreasing the value to speed up the player.

**Review by lilvedaes — APPROVED** [review]
It works perfectly! work of art c:

**Pull request merged**
