### PR TITLE
Import and place Assets & changes to level design

### PR DESCRIPTION
**Pull request by judy-n**
- Imported the models
- Placed platforms and decorated the level
- Made some changes to the location of platforms to make it more doable with the new mechanic

### CODE REVIEW

**Review by lilvedaes — COMMENTED** [review]
It looks gorgeous! I will officially trust you with level aesthetics, love the creativity around placing platforms and assets. My only comment is: be careful about the merge especially because of the new music, make sure it works by rebasing or merging dev with the new midi into your branch. Also, is it possible to add one of the sky boxes as the background?

**Comment by judy-n** [comment]
> It looks gorgeous! I will officially trust you with level aesthetics, love the creativity around placing platforms and assets. My only comment is: be careful about the merge especially because of the new music, make sure it works by rebasing or merging dev with the new midi into your branch. Also, is it possible to add one of the sky boxes as the background?

oops! I had the skybox but forgot to push those assets. could you try checking it now? :)

**Review by lilvedaes — APPROVED** [review]
Amazing!

**Review by jamilfaisal — APPROVED** [review]
Good poop*

**Pull request merged**
