### PR TITLE
Add Yarnball VFX and Adjust Player Shadow

### PR DESCRIPTION
**Pull request by jamilfaisal**
- Adjust lighting to make player shadow appear directly below the player
- Add URP to make player shadow appear on the switching platforms
- Add VFX for the yarnball

### CODE REVIEW

**Review by lilvedaes — COMMENTED** [review]
Shadow and yarn ball look great!!
I have two comments:
1. For some reason the box at the end looks like this, maybe it was an asset-importing issue? I can not see the cat hole clearly anymore and the colour appears to have changed. 
image

2. I think they also gave the vfx for the checkpoint (cat tree), could that be added here as well?

**Comment by jamilfaisal** [comment]
> Shadow and yarn ball look great!! I have two comments:
> 
> 1. For some reason the box at the end looks like this, maybe it was an asset-importing issue? I can not see the cat hole clearly anymore and the colour appears to have changed.
>    image
> 2. I think they also gave the vfx for the checkpoint (cat tree), could that be added here as well?

Fixed the endbox. Ill wait for the other PR to merge before doing the cat tree vfx

**Comment by jamilfaisal** [comment]
> Shadow and yarn ball look great!! I have two comments:
> 
> 1. For some reason the box at the end looks like this, maybe it was an asset-importing issue? I can not see the cat hole clearly anymore and the colour appears to have changed.
>    image
> 2. I think they also gave the vfx for the checkpoint (cat tree), could that be added here as well?

Added VFX for the cat tree

**Comment by judy-n** [comment]
I love how the checkpoints stand out now!!

**Comment by judy-n** [comment]
I have small polishing comments:

First, is it easy to make the glowing effect around the checkpoint more transparent? I feel like the glowing could be less white and more subtle. If it requires actually changing the texture or something then whatever it's not a huge deal, it's just a detail and already a huge improvement. 

Screen Shot 2022-11-01 at 8 58 11 PM

**Comment by judy-n** [comment]
Another thing I noticed: there's a faint transparent rectangle around the yarn ball, it was kind of noticeable in the gameplay
Screen Shot 2022-11-01 at 8 58 49 PM

**Review by lilvedaes — APPROVED** [review]
I approve if Judy's comments are applied

**Comment by jamilfaisal** [comment]
Addressed all of Judy's comments

**Review by judy-n — APPROVED** [review]
LGTM! good work

**Pull request merged**
