### PR TITLE
Fix settings menu and countdown for level two, Add new level two music and midi file, and level decorations (and other fixes)

### PR DESCRIPTION
**Pull request by jamilfaisal**

### CODE REVIEW

**Review by lilvedaes — CHANGES_REQUESTED** [review]
Make sure the cinemachine virtual cam has these settings:
![image](https://user-images.githubusercontent.com/28767278/206088238-2197957c-3f4d-4faa-bdb6-c9bfd6e32057.png

**Review by lilvedaes — COMMENTED** [review]
Also noticed when you respawn, the left and right movements only get you a Nice!, you cant get a purrfect on them again.

**Review by lilvedaes — COMMENTED** [review]
Alsoo, I do think we need to add some arrows in this midi, maybe not JUMP and L/R but I do think we need stomp arrows since we don't have a graphic indicator of that yet

**Comment by Gavin-L26** [comment]
> 

This problem is actually also happens in level one. It's just a bug on the checkpoint code, I've fixed it on the stomp branch.

**Comment by Gavin-L26** [comment]
> Also noticed when you respawn, the left and right movements only get you a Nice!, you cant get a purrfect on them again.

This problem actually also happens in level one. It's just a bug on the checkpoint code, I've fixed it on the stomp branch.

**Comment by jamilfaisal** [comment]
> Alsoo, I do think we need to add some arrows in this midi, maybe not JUMP and L/R but I do think we need stomp arrows since we don't have a graphic indicator of that yet

Kk Ill message griffin

**Review by Gavin-L26 — COMMENTED** [review]
The scene decoration looks good to me!
There are some MIDI level design problems that can be fixed later(
- I think double side movement without platform between might be a bit unforgiving
- I think I saw fish treats that are not on the correct lanes
- Some section's jump input requires to press jump even before you can land)

**Comment by jamilfaisal** [comment]
> The scene decoration looks good to me! There are some MIDI level design problems that can be fixed later(
> 
> * I think double side movement without platform between might be a bit unforgiving
> * I think I saw fish treats that are not on the correct lanes
> * Some section's jump input requires to press jump even before you can land)

Agreed. Already mentioned it to griffin

**Review by Gavin-L26 — APPROVED** [review]
All good!

**Review by lilvedaes — APPROVED** [review]
Amazing c:

**Pull request merged**
