### PR TITLE
Hide Mouse Button When Controller Is Pressed in Main Menu

### PR DESCRIPTION
**Pull request by jamilfaisal**
Mouse appears and disappears based on if the controller or keyboard or mouse are last interacted with (in main menu)

### CODE REVIEW

**Review by lilvedaes — APPROVED** [review]
LGTM c:

**Review by judy-n — COMMENTED** [review]
Mouse is disappearing correctly once I use my controller, but there's a bug

So when I'm using a controller, for example in the pause screen, if I select options using the controller and then try to use my mouse to select stuff, the cursor appears but it starts wiggling and I can't really control it. This happens for both pause and main menu screen.

so your fix is good but it seems to break if I decide to use the mouse when my controller was recently used

**Comment by jamilfaisal** [comment]
> 

I can't replicate this bug on my end because I think it's performance related. I adjusted the method to run every 500 ms instead of every frame (it's not as tight as before sadly). Let me know if the bug is fixed!

**Comment by jamilfaisal** [comment]
Turns out it wasn't performance related. The PS4 controller connected to PC constantly sends input which messed with my algorithm. Reimplemented everything using the new Unity input system and that should fix the issue

**Review by judy-n — APPROVED** [review]
LGTM :)

**Pull request merged**
