### PR TITLE
Implement stomp mechanic

### PR DESCRIPTION
**Pull request by judy-n**
- Added stomp mechanic (when you click "R") -> feel free to suggest other keys
- The force of the stomp is set by stompForce variable, try it out and let me know if you think it's too strong/too weak

### CODE REVIEW

**Comment by jamilfaisal** [comment]
I like it :) Can't wait to see the animation for it

**Review by jamilfaisal — APPROVED** [review]

**Review by lilvedaes — CHANGES_REQUESTED** [review]
Looks good. I know our main way to play this will be controller, but I think its worth it to change the key from R to E, feels more ergonomic.

**Comment by jamilfaisal** [comment]
> @lilvedaes 

I was thinking "slow down" tempo would be "Q" and "speed up" tempo would be "E"
I guess stomp can be "Ctrl" since we don't have a "duck" mechanic?

**Comment by judy-n** [comment]
> Looks good. I know our main way to play this will be controller, but I think its worth it to change the key from R to E, feels more ergonomic.

As per our discussion, I replaced it with "Tab" :)

**Comment by lilvedaes** [comment]
Approved!

**Pull request merged**
