### PR TITLE
Double jump and ramp adjustment

### PR DESCRIPTION
**Pull request by lilvedaes**
Added double jump feature by pressing the space bar again when in the air and adjusted the final two ramps for better visibility. Also added save jump for when you fall off a platform: you get one half jump if you have not jumped yet and have just fallen.

### CODE REVIEW

**Comment by jamilfaisal** [comment]
The ramps look much better now! Nice work :)
I think the second jump should be toned down a bit (the player can cover wayyyyyyyyyyyyyyyyyyyy too much distance). It should be a weaker version of the main jump, maybe half the height. (also makes sense bc the cat isn't using the ground as a solid object to push itself off from)

**Review by jamilfaisal — APPROVED** [review]
Great work!!!

**Review by judy-n — APPROVED** [review]
LGTM! Love how the double jump is helpful but not too OP :)

**Comment by jamilfaisal** [comment]
Double jump and Save jumps don't work on Xbox controller.

Player can jump off the Respawner platforms (as much as they can before they respawn)

**Review by jamilfaisal — CHANGES_REQUESTED** [review]
...Idk why Github wants me to write a comment here, but ok fix the bugs mentioned in my other comment please :)

**Comment by lilvedaes** [comment]
> Player can jump off the Respawner platforms (as much as they can before they respawn)

By respawner platforms do you mean all the platforms? Is the cat able to jump as much as they want after falling?

**Comment by jamilfaisal** [comment]
> > Player can jump off the Respawner platforms (as much as they can before they respawn)
> 
> By respawner platforms do you mean all the platforms? Is the cat able to jump as much as they want after falling?

There are "Respawner" platforms that respawn the player after a certain delay. The player is supposed to fall through them into infinity, but if you mash space then the player will start jumping on the platforms (and then respawn). Pretty sure it applies to all the Respawner platforms. 

Yes, in the beginning, I fell off and mashed space and i was jumping on air a bunch of times before I respawned

**Comment by lilvedaes** [comment]
Oh alright, that probably has to do with how we're identifying that we are grounded. I am not sure if the small jump will be finished by tomorrow's build then because there's still the GDD to be done. Should I undo the small jump and merge just the double jump (with added controller input) if there turns out to not be time?

**Comment by jamilfaisal** [comment]
> Oh alright, that probably has to do with how we're identifying that we are grounded. I am not sure if the small jump will be finished by tomorrow's build then because there's still the GDD to be done. Should I undo the small jump and merge just the double jump (with added controller input) if there turns out to not be time?

Yeah I'd say undo it and make a task in trello to pick up later. We don't wanna make the game too easy and I think this "save" jump risks that

**Comment by judy-n** [comment]
Double jump should now be working on controller! @jamilfaisal try it out if you get the chance

**Comment by jamilfaisal** [comment]
> Double jump should now be working on controller! @jamilfaisal try it out if you get the chance

Nice! Works on my switch controller.
I don't think these spaces were there in the dev branch...
image

**Comment by lilvedaes** [comment]
> > Double jump should now be working on controller! @jamilfaisal try it out if you get the chance
> 
> Nice! Works on my switch controller. I don't think these spaces were there in the dev branch... image

Spaces must be from readjusting the position, let me fix that.

**Review by jamilfaisal — APPROVED** [review]

**Pull request merged**
